#1 build react app
FROM node:16 AS build

WORKDIR /fmdeploy_frontend

ADD . /fmdeploy_frontend
ADD package.json /package.json
ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN npm install
RUN npm run build

#2 build the final image and copy the react build files
FROM nginx:1.21.4

COPY --from=build /fmdeploy_frontend/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]